### ISSUE TITLE
Change the & to | in text after Ex 11 in notebook 02

### ISSUE THREAD

**Issue by magitz** [PracticumAI/python-for-ai#12]
This: 
### Combining multiple criteria

Multiple criteria can be combined using either the `&` or `|` symbols:
* C1 `&` C2: This will select rows that match **both** criteria C1 **and** C2.
* C1 `&` C2: This will select rows that match **either** criteria C1 **or** C2.

Shoould be:

### Combining multiple criteria

Multiple criteria can be combined using either the `&` or `|` symbols:
* C1 `&` C2: This will select rows that match **both** criteria C1 **and** C2.
* C1 `|` C2: This will select rows that match **either** criteria C1 **or** C2.

**Comment by ilutticken** [comment]
Switched the symbols.
