### ISSUE TITLE
Exercise 11 in 02 file

### ISSUE THREAD

**Issue by dabrennan** [PracticumAI/python-for-ai#5]
Display the first 5 readings from European countries (country=='Europe'). No countries are equal to Europe, if you want countries in Europe it should be continent == 'Europe'

**Comment by magitz** [comment]
🤦 Thanks for opening the issue! I remember I ran into this earlier, but never opened an issue and forgot about it...
We'll get it fixed!

**Comment by magitz** [comment]
Closing as fixed. Will be merged into main soon. Thanks again @dabrennan!
